### ISSUE TITLE
Setup Internalisations

### ISSUE THREAD

**Issue by Nas84** [sogilis/Blog#11]
**Describe the solution you'd like**
We would like to setup internalisation in FR and in EN for the blog site. 
It should be based on the Hugo solutions

**Comment by jibidus** [comment]
Main question: should we display english article when french is selected?

**Comment by Nas84** [comment]
very good question 😃  i am more in favor to have either french or english but open to other solution

**Comment by jibidus** [comment]
What to do here:
- [ ] Set languages of each existing article. We can define a default language with `defaultContentLanguage` hugo config for files which does not define languages. But language can be set with content name (i.e. `about.en.md` or `about.fr.md`)
- [ ] Add button to switch language (see what it's done on [sogilis.com](https://sogilis.com))
- [ ] Multilangual multihost (see #57)
- [ ] When navigating to french article (from index), all site is translated to french (see #58)
- [ ] Translate header and footer (⚠️ do not forget mobile menu)
- [ ] Add `<html lang="en">`
- [ ] Find a way to set language in `Netlify CMS` ([seems not implemented yet](https://github.com/netlify/netlify-cms/issues/716))

ℹ️ Multi-language was removed with commit da54f8a3a5c74b1d72a6e4c339039e228ccf072e.
